---
Name: rootroutes
Before: '*'
---
Director:
  rules:
    '': 'Controller'
---
Name: coreroutes
Before: '*'
After:
  - '#rootroutes'
  - '#modelascontrollerroutes'
---
Director:
  rules:
    'Security//$Action/$ID/$OtherID': 'SilverStripe\Security\Security'
    'CMSSecurity//$Action/$ID/$OtherID': 'SilverStripe\Security\CMSSecurity'
    'dev': 'DevelopmentAdmin'
    'interactive': 'SapphireREPL'
    'InstallerTest//$Action/$ID/$OtherID': 'InstallerTest'
    'JSTestRunner//$Action/$ID/$OtherID': 'JSTestRunner'
    'SapphireInfo//$Action/$ID/$OtherID': 'SapphireInfo'
    'SapphireREPL//$Action/$ID/$OtherID': 'SapphireREPL'
---
Name: adminroutes
Before: '*'
After:
  - '#rootroutes'
  - '#coreroutes'
  - '#modelascontrollerroutes'
---
Director:
  rules:
    'admin': 'AdminRootController'
